### ISSUE TITLE
Colon : character in strings break syntax highlighting

### ISSUE THREAD

**Issue by nrocco** [stephpy/vim-yaml#8] opened 2017-05-16 17:28 UTC
<img width="442" alt="screen shot 2017-05-16 at 19 26 29" src="https://cloud.githubusercontent.com/assets/694012/26119473/991a237a-3a6d-11e7-8baf-587196f52adc.png">

See above screenshot. Line 5 contains a string in double quotes. The string uses a `:` character.

Syntax highlighting is broken as you can see on lines 7 and 8, up until the next `"` character.

Replacing the double quotes in line 5 with single quotes has the same effect.

**Comment by stephpy** [comment] 2017-05-17 07:07
Hi

Indeed, I have to investigate to fix this issue.

**Comment by stephpy** [comment] 2017-05-17 07:11
@nrocco what is you colorscheme ? I can't reproduce it with `vividchalk` 

![capture d ecran 2017-05-17 a 09 10 45](https://cloud.githubusercontent.com/assets/232744/26142424/bbfe2ecc-3ae0-11e7-993e-63c6952b6da4.png)

It's probably not the colorscheme, but I just want to be sure ...

**Comment by nrocco** [comment] 2017-05-17 09:06
Hi @stephpy,

Thanks for looking into this! I did attempt to fix it myself and create a PR but I know too little about vim syntax files :)

I am using colorscheme `onedark`. See https://github.com/joshdick/onedark.vim

I tried to use a vim built-in colorscheme `industry` and I get similar highlighting issues 9see screenshot)

![screen shot 2017-05-17 at 11 05 13](https://cloud.githubusercontent.com/assets/694012/26146511/b7f69aac-3af0-11e7-9292-dd18a9b5156f.png)

**Comment by jwoos** [comment] 2017-09-07 20:33
I had the same issue although with single quotations instead of double
<img width="245" alt="screen shot 2017-09-07 at 4 32 27 pm" src="https://user-images.githubusercontent.com/8202351/30183931-37c0cada-93ea-11e7-8f2c-f4fb4430da8d.png">

**Comment by jwoos** [comment] 2017-09-07 20:42
I made a PR to address this issue, it's my first time working with the highlighting in vim but it looks like a pretty straightforward Regex issue so I gave it a shot

https://github.com/stephpy/vim-yaml/pull/9

**Comment by stephpy** [comment] 2017-09-08 07:15
Thanks, I merged your PR.

**Closed by stephpy** 2017-09-08 07:15 UTC
